theme = "z4p5a9"

[editor]
line-number = "relative"
true-color = true
undercurl = true
clipboard-provider = "pasteboard"
cursorline = true
end-of-line-diagnostics = "hint"
bufferline = "multiple"
popup-border = "all"
auto-pairs = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.statusline]
left = [
  "mode",
  "version-control",
  "file-base-name",
  "read-only-indicator",
  "file-modification-indicator",
  "spacer",
  "spinner",
]
center = []
right = ["diagnostics", "position", "file-type"]
separator = "   "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["error"]

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
A-w = "move_next_sub_word_start"
A-b = "move_prev_sub_word_start"
A-e = "move_next_sub_word_end"

C-y = "scroll_up"
C-e = "scroll_down"

X = "extend_line_above"
C-g = ":sh tmux popup -E -d '#{pane_current_path}' -w 90%% -h 90%% gitu"
