[tools]
java = "zulu-17.66.19.0"
elixir = "latest"
erlang = "latest"

nodejs = "lts/jod"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"

bun = "latest"
op = "latest"

rust = "latest"

"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"aqua:typst/typst" = "latest"
"aqua:cli/cli" = "latest" # GitHub `gh` cli
